# Party taken from :
# https://raw.githubusercontent.com/libSDL2pp/libSDL2pp/master/.appveyor.yml
version: '{branch}.{build}'
os: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - MAKE_ARGS: OS=windows ARCH=64 CC=cl
    PREFIX: c:\usr_msvc
    MSVC:
    MINGW32: rem
  - MAKE_ARGS: OS=windows ARCH=32 CC=gcc
    PREFIX: c:\usr_mingw32
    MINGW32:
    MSVC: rem
cache:
  - c:\usr_msvc -> appveyor.yml
  - c:\usr_mingw32 -> appveyor.yml
before_build:
  - |-
    set MINGW32_ARCH=i686-w64-mingw32
  - if exist %PREFIX% set NEEDDEPENDS=rem

  # Depends
  - |-
    %NEEDDEPENDS% mkdir %PREFIX%\include\SDL2
    %NEEDDEPENDS% mkdir %PREFIX%\lib
    %NEEDDEPENDS% cd %TEMP%
    %NEEDDEPENDS% appveyor DownloadFile https://sourceforge.net/projects/gnuwin32/files/gettext/0.14.4/gettext-0.14.4-lib.zip
    %NEEDDEPENDS% mkdir gettext-0.14.4-lib
    %NEEDDEPENDS% move gettext-0.14.4-lib.zip gettext-0.14.4-lib
    %NEEDDEPENDS% cd gettext-0.14.4-lib
    %NEEDDEPENDS% 7z x gettext-0.14.4-lib.zip > nul
    %NEEDDEPENDS% copy include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy lib\* %PREFIX%\lib > nul
    %NEEDDEPENDS% cd ..


  # Depends for MSVC
  - |-
    %NEEDDEPENDS% %MSVC% set VS_DIR="C:\Program Files (x86)\Microsoft Visual Studio 14.0"
    %NEEDDEPENDS% %MSVC% %VS_DIR%\Common7\Tools\vsvars32.bat
    %NEEDDEPENDS% %MSVC% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
    %NEEDDEPENDS% %MSVC% 7z x SDL2-devel-2.0.4-VC.zip > nul
    %NEEDDEPENDS% %MSVC% copy SDL2-2.0.4\include\* %PREFIX%\include\SDL2 > nul
    %NEEDDEPENDS% %MSVC% copy SDL2-2.0.4\lib\x86\* %PREFIX%\lib > nul
    %NEEDDEPENDS% %MSVC% xcopy %PREFIX%\lib\* %VS_DIR%\VC\lib /s /e > nul
    %NEEDDEPENDS% %MSVC% xcopy %PREFIX%\include\* %VS_DIR%\VC\include /s /e > nul
    %NEEDDEPENDS% %MSVC% set PATH=c:\mingw\bin;%VS_DIR%\VC\bin;%PATH%

  # Depends for MinGW32
  - |-
    %NEEDDEPENDS% %MINGW32% choco install -y mingw -x86 > nul
    %NEEDDEPENDS% %MINGW32% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
    %NEEDDEPENDS% %MINGW32% 7z x SDL2-devel-2.0.4-mingw.tar.gz > nul
    %NEEDDEPENDS% %MINGW32% 7z x SDL2-devel-2.0.4-mingw.tar > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\include\SDL2\* %PREFIX%\include\SDL2 > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\lib\*.a %PREFIX%\lib > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\bin\*.dll %PREFIX%\lib > nul
    %NEEDDEPENDS% %MINGW32% xcopy %PREFIX%\lib\* c:\tools\mingw32\%MINGW32_ARCH%\lib /s /e > nul
    %NEEDDEPENDS% %MINGW32% xcopy %PREFIX%\include\* c:\tools\mingw32\%MINGW32_ARCH%\include /s /e > nul
    %NEEDDEPENDS% %MINGW32% set PATH=c:\tools\mingw32\bin;%PATH%
    %NEEDDEPENDS% %MINGW32% dir c:\tools
    %NEEDDEPENDS% %MINGW32% dir c:\tools\mingw32
    %NEEDDEPENDS% %MINGW32% dir c:\tools\mingw32\bin


build_script:
  # build
  - |-
    cd %APPVEYOR_BUILD_FOLDER%
    %MSVC% c:\mingw\bin\mingw32-make %MAKE_ARGS%
    %MINGW32% mingw32-make %MAKE_ARGS%

after_build:
  - git status
