# Partly taken from :
# https://raw.githubusercontent.com/libSDL2pp/libSDL2pp/master/.appveyor.yml
version: '{branch}.{build}'
os: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - PREFIX: c:\usr_msvc
    MSVC:
    MINGW32: rem
  - PREFIX: c:\usr_mingw32
    MINGW32:
    MSVC: rem
cache:
  - c:\usr_msvc -> appveyor.yml
  - c:\usr_mingw32 -> appveyor.yml
before_build:
  - |-
    set MINGW32_ARCH=i686-w64-mingw32
  - if exist %PREFIX% set NEEDDEPENDS=rem

    # %NEEDDEPENDS% appveyor DownloadFile https://sourceforge.net/projects/gnuwin32/files/gettext/0.14.4/gettext-0.14.4-lib.zip
  # Depends
  - |-
    %NEEDDEPENDS% mkdir %PREFIX%\include\SDL2
    %NEEDDEPENDS% mkdir %PREFIX%\lib
    %NEEDDEPENDS% cd %TEMP%
    %NEEDDEPENDS% curl -fsSL -o gettext-0.14.4-lib.zip https://sourceforge.net/projects/gnuwin32/files/gettext/0.14.4/gettext-0.14.4-lib.zip
    %NEEDDEPENDS% mkdir gettext-0.14.4-lib
    %NEEDDEPENDS% move gettext-0.14.4-lib.zip gettext-0.14.4-lib
    %NEEDDEPENDS% cd gettext-0.14.4-lib
    %NEEDDEPENDS% 7z x gettext-0.14.4-lib.zip > nul
    %NEEDDEPENDS% copy include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy lib\* %PREFIX%\lib > nul
    %NEEDDEPENDS% cd ..


  # Depends for MSVC
  - |-
    %MSVC% set VS_DIR="C:\Program Files (x86)\Microsoft Visual Studio 14.0"
    %MSVC% %VS_DIR%\VC\vcvarsall.bat x86
    %NEEDDEPENDS% %MSVC% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
    %NEEDDEPENDS% %MSVC% 7z x SDL2-devel-2.0.4-VC.zip > nul
    %NEEDDEPENDS% %MSVC% copy SDL2-2.0.4\include\* %PREFIX%\include\SDL2 > nul
    %NEEDDEPENDS% %MSVC% copy SDL2-2.0.4\lib\x86\* %PREFIX%\lib > nul
    %MSVC% xcopy %PREFIX%\lib\* %VS_DIR%\VC\lib /s /e > nul
    %MSVC% xcopy %PREFIX%\include\* %VS_DIR%\VC\include /s /e > nul
    %MSVC% set PATH=c:\mingw\bin;%VS_DIR%\VC\bin;%PATH%

  # Depends for MinGW32
  - |-
    %MINGW32% choco install -y mingw -x86 > nul
    %NEEDDEPENDS% %MINGW32% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
    %NEEDDEPENDS% %MINGW32% 7z x SDL2-devel-2.0.4-mingw.tar.gz > nul
    %NEEDDEPENDS% %MINGW32% 7z x SDL2-devel-2.0.4-mingw.tar > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\include\SDL2\* %PREFIX%\include\SDL2 > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\lib\*.a %PREFIX%\lib > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\bin\*.dll %PREFIX%\lib > nul
    %MINGW32% xcopy %PREFIX%\lib\* c:\tools\mingw32\%MINGW32_ARCH%\lib /s /e > nul
    %MINGW32% xcopy %PREFIX%\include\* c:\tools\mingw32\%MINGW32_ARCH%\include /s /e > nul
    %MINGW32% set PATH=c:\tools\mingw32\bin;%PATH%
    %MINGW32% dir c:\tools
    %MINGW32% dir c:\tools\mingw32
    %MINGW32% dir c:\tools\mingw32\bin


build_script:
  # build
  - |-
    cd %APPVEYOR_BUILD_FOLDER%
    rem Dirty workaround from fe-setup.bat
    setx FE_PATH=%APPVEYOR_BUILD_FOLDER%
    setx PATH "%FE_PATH%;%path%;"
    cd examples/cube
    ..\..\bin\fe-build j=8 show_all_cmd=yes

after_build:
  - git status
