# Party taken from :
# https://raw.githubusercontent.com/libSDL2pp/libSDL2pp/master/.appveyor.yml
version: '{branch}.{build}'
os: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - MAKE_ARGS: OS=windows ARCH=64 CC=cl
    PREFIX: c:\usr_msvc
    MSVC:
    MINGW32: rem
  - MAKE_ARGS: OS=windows ARCH=32 CC=gcc
    PREFIX: c:\usr_mingw32
    MINGW32:
    MSVC: rem
cache:
  - c:\usr_msvc -> appveyor.yml
  - c:\usr_mingw32 -> appveyor.yml
before_build:
  - |-
    set MINGW32_ARCH=i686-w64-mingw32
    set WINDBG_DIR="C:\Program Files (x86)\Windows Kits\8.1\Debuggers\x86"
    set DBGHELP_H="C:\Program Files (x86)\Windows Kits\8.1\include\um\DbgHelp.h"
  - if exist %PREFIX% set NEEDDEPENDS=rem

  # Depends
  - |-
    %NEEDDEPENDS% mkdir %PREFIX%\include\SDL2
    %NEEDDEPENDS% mkdir %PREFIX%\lib
    %NEEDDEPENDS% cd %TEMP%

  # Depends for MSVC
  - |-
    %NEEDDEPENDS% %MSVC% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
    %NEEDDEPENDS% %MSVC% 7z x SDL2-devel-2.0.4-VC.zip > nul
    %NEEDDEPENDS% %MSVC% copy SDL2-2.0.4\include\* %PREFIX%\include\SDL2 > nul
    %NEEDDEPENDS% %MSVC% copy SDL2-2.0.4\lib\x86\* %PREFIX%\lib > nul
    %NEEDDEPENDS% %MSVC% appveyor DownloadFile https://sourceforge.net/projects/gnuwin32/files/gettext/0.14.4/gettext-0.14.4-lib.zip
    %NEEDDEPENDS% %MSVC% mkdir gettext-0.14.4-lib
    %NEEDDEPENDS% %MSVC% move gettext-0.14.4-lib.zip gettext-0.14.4-lib
    %NEEDDEPENDS% %MSVC% cd gettext-0.14.4-lib
    %NEEDDEPENDS% %MSVC% 7z x gettext-0.14.4-lib.zip > nul
    %NEEDDEPENDS% %MSVC% copy include\* %PREFIX%\include > nul
    %NEEDDEPENDS% %MSVC% copy lib\* %PREFIX%\lib > nul
    %NEEDDEPENDS% %MSVC% cd ..

  # Depends for MinGW32
  - |-
    %NEEDDEPENDS% %MINGW32% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
    %NEEDDEPENDS% %MINGW32% 7z x SDL2-devel-2.0.4-mingw.tar.gz > nul
    %NEEDDEPENDS% %MINGW32% 7z x SDL2-devel-2.0.4-mingw.tar > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\include\SDL2\* %PREFIX%\include\SDL2 > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\lib\*.a %PREFIX%\lib > nul
    %NEEDDEPENDS% %MINGW32% copy SDL2-2.0.4\%MINGW32_ARCH%\bin\*.dll %PREFIX%\lib > nul
    %NEEDDEPENDS% %MINGW32% copy %DBGHELP_H% %PREFIX%\include

build_script:
  # build
  - |-
    %MSVC% cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools"
    %MSVC% VSVARS32
    %MSVC% set "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin";%PATH%
    %MINGW32% set c:\mingw\bin;%PATH%
    cd %APPVEYOR_BUILD_FOLDER%
    mingw32-make %MAKE_ARGS%

after_build:
  - git status
