sudo: required
dist: trusty
branches:
  only:
    - master
    - android-ci
    - ios-ci
    - emscripten-ci
os:
  - linux
  - osx
language: c
compiler:
  - gcc
  - clang
before_install:
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ];   then . ./ci/travis/before_install-osx.sh; fi
install:
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/install-linux.sh; fi
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ];   then . ./ci/travis/install-osx.sh; fi
script:
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then bin/bash/fe-setup && . ~/.bashrc && cd examples/cube && fe-build j=1 show_all_cmd=yes target_linux64_${CC}=y target_linux64_${CC}_available=y; fi
  - if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ];   then bin/bash/fe-setup && . ~/.bashrc && cd examples/cube && fe-build j=1 show_all_cmd=yes target_osx_${CC}=y target_osx_${CC}_available=y; fi
