os:
- linux
language: c
compiler: gcc
before_install:
- yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
- sudo apt-get update -qq
install:
- sudo apt-get install -y libsdl2-dev
script:
- make clean; make -j3 OS=$TRAVIS_OS_NAME ARCH=64 CC=gcc
