d3d10_sample.exe: d3d10_sample.c ../../../include/fate/d3d/defs.h
	cl /nologo /I..\..\..\include d3d10_sample.c d3d10.lib csfml-graphics-2.lib csfml-system-2.lib csfml-window-2.lib gdi32.lib opengl32.lib user32.lib

