CCFLAGS = -std=c11 -idirafter include -idirafter include/contrib -Wall -Wno-format-security \
		 --emrun -s USE_SDL=2 -s ASYNCIFY=1 -s ASSERTIONS=2 -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 -s FORCE_FILESYSTEM=1
CCDEBUGFLAGS = $(CCFLAGS) -g \
			   -DFE_DEBUG_BUILD -DFE_ENABLE_TRACING
GLEWFLAGS = -DGLEW_STATIC -DGLEW_NO_GLU # -O0
CCRELEASEFLAGS = $(CCFLAGS) -O3 -DNDEBUG
CCOBJ = -c 
CCOUT_OBJ = -o 
CCOUT_EXE = -o 
LDLIBS=
