gnumake  :=mingw32-make
gnumake  :=make
gnum4    :=m4 --gnu 
vcvars32 :=vcvars32.bat
vcvars64 :=vcvars64.bat
android  :=android
ndk_build:=ndk-build
ant      :=ant
rc       :=rc
windres  :=windres

ifeq ($(host_os),windows)
windows32_cl_cc :=cl /nologo
windows32_cl_as :=ml /nologo /DX86
windows64_cl_cc :=cl /nologo
windows64_cl_as :=ml64 /nologo /DX64
target_windows64_gcc_available := yes
target_windows32_gcc_available := yes
#target_windows32_cl_available := yes
target_windows64_cl_available := yes
windows32_gcc_cc  :=gcc -m32
windows64_gcc_as  :=as
windows64_gcc_cc  :=gcc -m64
windows64_gcc_as  :=as
windows32_clang_cc:=clang -m32
windows32_clang_as:=as
windows64_clang_cc:=clang -m64
windows64_clang_as:=as
linux32_gcc_cc    :=linux-gcc -m32
linux32_gcc_as    :=linux-as
linux64_gcc_cc    :=linux-gcc -m64
linux64_gcc_as    :=linux-as
linux32_clang_cc  :=linux-clang -m32
linux32_clang_as  :=linux-as
linux64_clang_cc  :=linux-clang -m64
linux64_clang_as  :=linux-as
osx_gcc_cc        :=osx-gcc
osx_gcc_as        :=osx-as
osx_clang_cc      :=osx-clang
osx_clang_as      :=osx-as
ios_cc            :=ios-clang
ios_as            :=ios-as
emscripten_cc     :=emcc
emscripten_as     :=
endif
ifeq ($(host_os),linux)
windows32_cl_cc :=vc-cl /nologo
windows32_cl_as :=vc-ml /nologo /DX86
windows64_cl_cc :=vc-cl /nologo
windows64_cl_as :=vc-ml64 /nologo /DX64
windows32_gcc_cc  :=mingw-gcc -m32
windows64_gcc_as  :=mingw-as
windows64_gcc_cc  :=mingw-gcc -m64
windows64_gcc_as  :=mingw-as
windows32_clang_cc:=mingw-clang -m32
windows32_clang_as:=mingw-as
windows64_clang_cc:=mingw-clang -m64
windows64_clang_as:=mingw-as
linux32_gcc_cc    :=gcc -m32
linux32_gcc_as    :=as
linux64_gcc_cc    :=gcc -m64
linux64_gcc_as    :=as
target_linux64_gcc_available := yes
target_linux64_clang_available := yes
target_emscripten_available := yes
target_android_available := yes
linux32_clang_cc  :=clang -m32
linux32_clang_as  :=as
linux64_clang_cc  :=clang -m64
linux64_clang_as  :=as
osx_gcc_cc        :=osx-gcc
osx_gcc_as        :=osx-as
osx_clang_cc      :=osx-clang
osx_clang_as      :=osx-as
ios_cc            :=ios-clang
ios_as            :=ios-as
emscripten_cc     :=emcc
emscripten_as     :=
endif
ifeq ($(host_os),osx)
windows32_cl_cc :=vc-cl /nologo
windows32_cl_as :=vc-ml /nologo /DX86
windows64_cl_cc :=vc-cl /nologo
windows64_cl_as :=vc-ml64 /nologo /DX64
windows32_gcc_cc  :=mingw-gcc -m32
windows64_gcc_as  :=mingw-as
windows64_gcc_cc  :=mingw-gcc -m64
windows64_gcc_as  :=mingw-as
windows32_clang_cc:=mingw-clang -m32
windows32_clang_as:=mingw-as
windows64_clang_cc:=mingw-clang -m64
windows64_clang_as:=mingw-as
linux32_gcc_cc    :=linux-gcc -m32
linux32_gcc_as    :=linux-as
linux64_gcc_cc    :=linux-gcc -m64
linux64_gcc_as    :=linux-as
linux32_clang_cc  :=linux-clang -m32
linux32_clang_as  :=linux-as
linux64_clang_cc  :=linux-clang -m64
linux64_clang_as  :=linux-as
osx_gcc_cc        :=gcc
osx_gcc_as        :=as
osx_clang_cc      :=clang
osx_clang_as      :=as
ios_cc            :=clang
ios_as            :=as
emscripten_cc     :=emcc
emscripten_as     :=
endif
